--PROCEDURE PARA REGISTRAR ENTRADA DE MERCADORIA NO ESTOQUE E REGISTRAR NO LOG DE ENTRADA
CREATE OR ALTER PROCEDURE PR_REGISTRA_ENTRADA_GERA_LOG
@P_ID_MERCADORIA			INT,
@P_QUANTIDADE				INT, 
@P_DATA_ENTRADA				DATE,
@P_HORA_ENTRADA				TIME,
@P_LOCAL					VARCHAR(100)
AS
BEGIN

BEGIN TRANSACTION
	BEGIN TRY
				IF EXISTS (SELECT 1 FROM TB_ESTOQUE WHERE ID_MERCADORIA = @P_ID_MERCADORIA)
					BEGIN
						UPDATE TB_ESTOQUE
						SET QUANTIDADE = QUANTIDADE + @P_QUANTIDADE
						WHERE ID_MERCADORIA = @P_ID_MERCADORIA
					END
				ELSE
					BEGIN
						INSERT INTO TB_ESTOQUE (ID_MERCADORIA, QUANTIDADE)
						VALUES (@P_ID_MERCADORIA, @P_QUANTIDADE)
					END
						
							INSERT INTO LOG_ENTRADA_MERCADORIA
							SELECT 
							 ID
							,ID_MERCADORIA
							,@P_QUANTIDADE
							,@P_DATA_ENTRADA
							,@P_HORA_ENTRADA
							,@P_LOCAL
							FROM TB_ESTOQUE
							WHERE ID_MERCADORIA = @P_ID_MERCADORIA
			COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
	END CATCH
END

