--PROCEDURE PARA INSERIR E ATUALIZAR O ESTOQUE E REGISTRAR NO LOG
CREATE OR ALTER PROCEDURE PR_REGISTRA_SAIDA_GERA_LOG
@P_ID_MERCADORIA			INT,
@P_QUANTIDADE				INT, 
@P_DATA_SAIDA				DATE,
@P_HORA_SAIDA				TIME,
@P_LOCAL					VARCHAR(100)
AS
BEGIN


BEGIN TRANSACTION
	BEGIN TRY
			UPDATE TB_ESTOQUE 
				SET QUANTIDADE = QUANTIDADE - @P_QUANTIDADE
				WHERE ID_MERCADORIA = @P_ID_MERCADORIA	
					
					INSERT INTO LOG_SAIDA_MERCADORIA
					SELECT 
					 ID
					,ID_MERCADORIA
					,@P_QUANTIDADE
					,@P_DATA_SAIDA
					,@P_HORA_SAIDA
					,@P_LOCAL
					FROM TB_ESTOQUE
					WHERE ID_MERCADORIA = @P_ID_MERCADORIA
			COMMIT
	END TRY
	BEGIN CATCH
		ROLLBACK
	END CATCH
END

