CREATE OR ALTER VIEW VW_RELATORIO_ENTRADA_E_SAIDA
AS
SELECT DISTINCT
 M.ID AS IdMercadoria
,M.NOME AS Mercadoria
,M.FABRICANTE AS Fabricante
,M.TIPO AS Tipo
,MONTH(E.DATA_ENTRADA) AS Mes
,SUM(E.QUANTIDADE) AS TotalEntrada
,0 AS TotalSaida
	FROM LOG_ENTRADA_MERCADORIA E
		INNER JOIN TB_MERCADORIAS M
			ON E.ID_MERCADORIA = M.ID
GROUP BY M.ID, M.NOME, M.FABRICANTE,M.TIPO, E.DATA_ENTRADA
UNION
SELECT DISTINCT
 M.ID AS IdMercadoria
,M.NOME AS Mercadoria
,M.FABRICANTE AS Fabricante
,M.TIPO AS Tipo
,MONTH(E.DATA_SAIDA) AS Mes
,0 AS TotalEntrada
,SUM(E.QUANTIDADE) AS TotalSaida
	FROM LOG_SAIDA_MERCADORIA E
		INNER JOIN TB_MERCADORIAS M
			ON E.ID_MERCADORIA = M.ID
GROUP BY M.ID, M.NOME, M.FABRICANTE,M.TIPO, E.DATA_SAIDA